### ISSUE TITLE
[BUG] `rapids_cpm_find` avoid package_needs_to_be_added check before `CPMFindPackage`

### ISSUE THREAD

**Issue by mdemoret-nv** [rapidsai/rapids-cmake#117]
The description of `rapids_cpm_find` makes it seem like it's nearly a drop in replacement for `CPMFindPackage` that adds functionality for tracking global dependencies and setting up correct exports. However, the function subtly changes the behavior of `CPMFindPackage` depending on whether this function has already been called, and overrides CPM functionality. This can lead to bugs that are difficult to diagnose if a user expects every call to `rapids_cpm_find` to function similarly to `CPMFindPackage`. 

The problem lies in this section of the function:
```
  if(package_needs_to_be_added)
    if(CPM_${name}_SOURCE)
      CPMAddPackage(NAME ${name} VERSION ${version} ${RAPIDS_UNPARSED_ARGUMENTS})
    else()
      CPMFindPackage(NAME ${name} VERSION ${version} ${RAPIDS_UNPARSED_ARGUMENTS})
    endif()
  endif()
```
If the user needs some variables set by `CPMFindPackage`, they may or may not be set depending on whether `rapids_cpm_find` has already been called or not. Consider this scenario, partially pulled from cuDF, where two dependencies each call `rapids_cpm_find` with the same arguments:
```
function(find_and_configure_libcudacxx VERSION)
    rapids_cpm_find(libcudacxx ${VERSION} ...)

    set(LIBCUDACXX_INCLUDE_DIR "${libcudacxx_SOURCE_DIR}/include" PARENT_SCOPE)
endfunction()

function(configure_cudf VERSION)
    find_and_configure_libcudacxx(VERSION)

    # This next line may fail!!!!
    file(COPY "${LIBCUDACXX_INCLUDE_DIR}/" DESTINATION "${CMAKE_BINARY_DIR}/include/libcudacxx")
endfunction()

function(configure_matx VERSION)
    rapids_cpm_find(libcudacxx ${VERSION} ...)
endfunction()
```
Everything works smoothly if the configure functions are called in this order:
```
configure_cudf(...)
configure_matx(...)
````
However, they fail if called in this order:
```
configure_matx(...)
configure_cudf(...) # ERROR: Cannot copy /include !!!
```
An error will be generated much later in the code because `libcudacxx_SOURCE_DIR` was never set in the second function call. I recently ran into this issue and it was difficult to debug what was happening because the error message and the cause of the error were very far apart and only showed up depending on the order some third party dependencies were added.

To fix this, I think any function that wraps a CPM function should:
1. Always call the wrapped CPM function
   a. CPM already has mechanisms to handle duplicate calls while still providing the same output
   b. Calling `CPMFindPackage` regardless of the value of `package_needs_to_be_added` ensures the correct variables are set with very little downsides
2. Do not call a different CPM function than the wrapped function
   a. i.e. `rapids_cpm_find` should call `CPMFindPackage` and never `CPMAddPackage` if `CPM_${name}_SOURCE` is set
   4. CPM already has mechanisms to call `CPMFindPackage` from `CPMAddPackage` and `CPMAddPackage` from `CPMFindPackage`. This behavior will only complicates or hides that behavior
3. Provide separate wrappers for each wrapped CPM function
   a. i.e. There should be a `rapids_cpm_find` to wrap `CPMFindPackage` and `rapids_cpm_add` to wrap `CPMAddPackage`
   b. This also helps with dependencies which always need to be added, even if they are found. Its not possible to use `rapids_cpm_find` in this scenario. (GLOG is an example of this. You must build from source if you want a custom log format)

In my opinion, these changes would make the functionality of `rapids_cpm_XXX` functions more clear, lead to less bugs, and make it easier to maintain the library for future updates to CPM.

**Comment by robertmaynard** [comment]
I think the plan of backing out the introduction of the behavior changes of `rapids_cpm_find` and introducing `rapids_cpm_add` should work. Do you agree @trxcllnt ?

**Comment by robertmaynard** [comment]
Thank you for tracking down this issue. This is a horrible confluence of issues.

After thinking about this more, are you sure that `CPM_${name}_SOURCE` is at fault? The reason why I ask is that this variable is never set by CPM itself but only used to control the behavior of `CPMFindPackage` if set by the user / rapids-cmake. In this case I see no setting of `CPM_cudf_source` to trigger this behavior.

I believe what is happening is just a classic bug of `CPMFindPackage` presumptions. In this case `cudf` has presumed that the `find_package` call will never suceed and `libcudacxx` will always be added as a source dependency. In your case matx has found a local libcudacxx and established that version in the CPM cache subsequently when `cudf` comes around it generates bad install commands since it didn't check `libcudacxx_ADDED` ( side note: cudf looks to not have this logic anymore ).

For background, this rapids-cmake feature was added to resolve the issue that CPM doesn't offer per project download controls. Instead it only offers `CPM_DOWNLOAD_ALL` which would effect any CPM calls that are issued by the package that was added.

While that is the case, I do agree that this implicit behavior change is non-standard and surprising. Does the following work for you:

1. We only enable the `CPM_${name}_SOURCE` behavior change for `rapids_cpm_find` behind a feature toggle ( env variable / cmake variable )

**Comment by mdemoret-nv** [comment]
> After thinking about this more, are you sure that CPM_${name}_SOURCE is at fault?

Maybe I could have been more clear. This was not the cause of the issue I was having. The cause is definitely `if(package_needs_to_be_added)`.

However, when looking at the code, I saw that as another potential issue that could hide some bugs by changing how CPM works. Since I saw two things changing the behavior of CPM, I made my issue about "Avoid altering the behavior of CPM" instead of "Remove package already added check".

>We only enable the CPM_${name}_SOURCE behavior change for rapids_cpm_find behind a feature toggle ( env variable / cmake variable )

I think this is a nice change but like I mentioned before, the issue is with checking if the package has been added before, and avoiding the second call to `CPMFindPackage`. We are seeing this behavior even when using `CPM_${name}_SOURCE`. So that change alone would not fix our issue.

With that out of the way, what is the reason for avoiding the second call to `CPMFindPackage`? I'm not sure how that fits in with your other issue about having per-package download options. And it seems to me that calling `CPMFindPackage` is pretty harmless since it already has its own check to avoid adding packages twice.

**Comment by robertmaynard** [comment]
> I think this is a nice change but like I mentioned before, the issue is with checking if the package has been added before, and avoiding the second call to CPMFindPackage. We are seeing this behavior even when using CPM_${name}_SOURCE. So that change alone would not fix our issue.

Correct the issue is that the avoidance of not calling CPMFindPackage a subsequent time fails to restore any of the CPM variables, which is a defect.

As for why `rapids_cpm_find` avoids calling `CPMFindPackage` for the same project multiple times. It was introduced to avoid issues that exist when `find_package` and `CPMFindPackage` are used to find the same project.

```
set(tree_ROOT "<path/on/disk>)
find_package( tree CONFIG)
 |---> find_package( leaf CONFIG )
CPMFindPacakge( leaf ....)
 ```
In this example the initial call of `find_package( leaf CONFIG )` will find an installed version based on the path in `tree_ROOT` given CMake's project ROOT nested search behavior. When `CPMFindPackage( leaf )` is executed it won't find the same installed version and instead try to add `leaf` source code, which fails as the targets of `leaf` already exist.

This workflow was being hit numerous times by RAPIDS projects when bringing in long chains of dependencies. Before this behavior was introduced projects would manually do a target check before the call to `rapids_cpm_find`. This has subtle issues where it causes a projects generated dependency tree to be incomplete.

But your workflow pattern is also valid/correct and needs to be supported as well.
I believe that the best option is that when we decide to early terminate we need to restore any CPM variables that might exist
so that `rapids_cpm_find` behaves the same way that CPM does when it early terminates.

**Comment by mdemoret-nv** [comment]
> But your workflow pattern is also valid/correct and needs to be supported as well.
I believe that the best option is that when we decide to early terminate we need to restore any CPM variables that might exist
so that rapids_cpm_find behaves the same way that CPM does when it early terminates.

I think thats fair. If you just call `cpm_export_variables` that should do the trick.
