### ISSUE TITLE
[FEA] support local repositories / directories with rapids_cpm_find

### ISSUE THREAD

**Issue by bsarden** [rapidsai/rapids-cmake#185]
When working with rapidsai projects, it can be difficult to overlay changes in the conda environment for transitive dependencies (e.g. cuCollections, cub, etc.). It would be great if we could override dependencies with our dirty checkouts for quick experiments.

Could we improve [versions.json](https://github.com/rapidsai/rapids-cmake/blob/branch-22.06/rapids-cmake/cpm/versions.json) (or provide an example if it already supports it) to allow users to override a repository with a local directory path. It seems like [rapids_cpm_find](https://github.com/rapidsai/rapids-cmake/blob/branch-22.06/rapids-cmake/cpm/find.cmake) might be a natural place for this, but I'm also not a cmake or conda expert (maybe this is already possible!). 

Thanks for your time :)

**Comment by robertmaynard** [comment]
You have a couple of options to use an existing local version of a project.

For projects that have a `<package-name>-config.cmake` in the build directory or  can specify  `-DCMAKE_PREFIX_PATH=<dir>` or `-D<Package_Name>_ROOT=<dir>` to tell CMake to search for the package in that location. 

If the project doesn't offer that, you can use `-DPM_DOWNLOAD_<Package>=ON -DCPM_<Package>_SOURCE=/path/to/pkg/src` this will cause the local source version to be used, and built as part of your project instead of the values in the `versions.json`

If CMake won't use the local version due to a version mismatch between the local version, and the one specified in `versions.json`. You can use [rapids_cpm_package_override](https://docs.rapids.ai/api/rapids-cmake/stable/command/rapids_cpm_package_override.html) to specify the new version value.
