### ISSUE TITLE
[BUG] Detect conda install even when using scikit-build, pick lib/ over lib64/

### ISSUE THREAD

**Issue by manopapad** [rapidsai/rapids-cmake#426]
**Description**

As noted on [this issue](https://github.com/conda/conda-build/issues/244#issuecomment-1024388227), rapids-cmake will always set the library directory to `lib/` (even if the system's native library directory is `lib64/`) when installing under a conda environment, to appease [cpython's requirement](https://docs.python.org/3/library/sys.html#sys.platlibdir) that third-party modules always be installed under `lib/`.

This is [not happening](https://github.com/nv-legate/cunumeric/issues/835) for our stack on RHEL installations (installed libraries erroneously end up under `$CONDA_PREFIX/lib64`).

The underlying issue appears to be that we're using `scikit-build`, and that is setting `CMAKE_INSTALL_PREFIX` to `_skbuild/<arch>/cmake-install` (the artifacts eventually make it to `$CONDA_PREFIX`). CMake only activates the python compatibility mode when `CMAKE_INSTALL_PREFIX` is equal to `$CONDA_PREFIX`, and in this case it is not.

Some of our cmake files were calling `include(GNUInstallDirs)` before `rapids_cmake_install_lib_dir()`, but changing that order didn't help. We were eventually able to work around this issue by explicitly setting `-DCMAKE_INSTALL_LIBDIR=lib`, but it would be best if `rapids-cmake` could recognize that automatically.

**Steps/Code to reproduce bug**

Get on a RHEL system (or VM/container) and do:

```
# install conda
git clone https://github.com/nv-legate/legate.core.git
cd legate.core
./scripts/generate-conda-envs.py --os linux --python 3.9 --ctk none --no-compilers --no-openmpi --no-ucx
conda env create -n legate -f environment-test-linux-py3.9.yaml
conda activate legate
./install.py --verbose
```

The output libraries, e.g. `liblgcore.so`, end up under `$CONDA_PREFIX/lib64`.

**Environment details**

- Environment location: We've encountered this on NERSC's Perlmutter, other users have reported this on local RHEL systems.
- CMake version: 3.26.3

**Comment by robertmaynard** [comment]
I am going to have to close this. The more generalized heuristic of presuming a conda location ( `lib` ) when on rhel + conda env variables is not possible.

That approach was originally used by me in CMake proper and broke numerous RHEL based distros ( https://gitlab.kitware.com/cmake/cmake/-/issues/22962 ) which provide conda for all users by default. In those cases all builds are 'inside' a conda env but not installing to the `CONDA_PREFIX`.

I don't think we can reliably say that `scikit-build` builds on RHEL with conda env variables means we are doing a conda build. As the fix for 22962 shows the `CONDA_PREFIX` on these machines is something like `/usr` and so we can't do something like see if we are using a conda provided compiler as on those machines we would yet again get a false positive.

Unless we can find a reliable heuristic for RHEL+CONDA we are going to have to explicitly specify the install lib dir in these cases.
