### ISSUE TITLE
[FEA] Nice to have: resource spec generation to be platform independent 

### ISSUE THREAD

**Issue by karthikeyann** [rapidsai/rapids-cmake#436]
https://github.com/rapidsai/rapids-cmake/blob/965321ee8323f77ffaa1bd6ff825d12245d55cd3/rapids-cmake/test/generate_resource_spec.cmake#L80

Can we make this platform independent? (to support windows compilation)

Here is a suggestion.
```
    set(pre_cmd ";")
    if(MSVC)
      set(pre_cmd "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat")
    endif()

    execute_process(COMMAND "${pre_cmd}" "&&" "${compiler}" "${eval_file}" ${compile_options} ${link_options} -o
                            "${eval_exe}" OUTPUT_VARIABLE compile_output
                    ERROR_VARIABLE compile_output COMMAND_ECHO STDOUT)
```
Related https://cmake.org/pipermail/cmake/2016-June/063685.html

**Comment by robertmaynard** [comment]
We can't encode the location of `vcvars64` like that since the location is selected by the user ( and also based on the MSVC version ). The `&&` aren't supported in execute_process as you aren't in a shell.

You should execute rapids-cmake from a shell that already has `vcvars64.bat` invoked, e.g. a Visual Studio developers shell.
